services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        offlinekey: "your_offline_key"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-liukuri
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: